name: sample

channels:
  - conda-forge/linux-64

dependencies:
  - python<=3.10.6
  - regex
  - lxml>=4.6.3
  - isodate==0.6.0
  - aniso8601==9.0.1
  - holidays==0.11.1
  - tabulate
  - numpy==1.22.0
  - pyparsing==3.0.9
  - pip
  - pip:
    - Arelle-release==2.2.0
